import './globals.css'
import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import Header from '@/components/header/header'

const noto = Noto_Sans({ 
  subsets: ['latin'],
  weight: '500'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <Header/>
        <main>
          {children}
        </main>
        <footer>

        </footer>
      </body>
    </html>
  )
}
